### ISSUE TITLE
Compose syntax with links doesn't work on multi-node installations

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1828]
When using compose syntax on multi-node installation:
```
    version: '2'
    services:
      dev-machine:
        image: 'nuxeo/che-workspace:8.10'
        links:
          - 'mongo:mongo'
          - 'redis:redis'
        depends_on:
          - mongo
          - redis
        environment:
          - NUXEO_DEV_MODE=true
          - 'NUXEO_TEMPLATES=default,mongodb'
          - NUXEO_PACKAGES=nuxeo-jsf-ui nuxeo-web-ui
            NUXEO_CUSTOM_PARAM=nuxeo.redis.enabled=true\nnuxeo.redis.host=redis\nnuxeo.mongodb.server=mongo
          - NUXEO_DATA=/opt/nuxeo/server/data
          - NUXEO_LOG=/opt/nuxeo/server/log
      mongo:
        image: mongo
      redis:
        image: redis
```

![nuxeo-compose-multinode](https://cloud.githubusercontent.com/assets/1636620/23255112/05d964ee-f9c3-11e6-9136-a1f8d51db7ad.png)

**Reproduction Steps:**

Use inlined compose

**Codenvy version:**   5.0.0-M7 (Puppet-based)
