### ISSUE TITLE
Volumes in compose

### ISSUE THREAD

**Issue by soanni** [codenvy/codenvy#897]
Hello Codenvy team,
Today we discussed with Brad possibility to implement volumes in Codenvy compose environments.
Let me share with you my thoughts about how it can be possibly implemented.
1. During installation Codenvy could create some folder on the host filesystem like /codenvy_volumes
2. When someone starts to create a workspace (for example, workspace_1) from compose Codenvy will create a subfolder /codenvy_volumes/workspace_1
3. Let assume that i have this compose file:

```
lhq-web:
    build:
      context: ./lhq/lhq-web/
      args:
        - JAVA_VERSION=7u80
        - JAVA_RELEASE=b15
        - TOMCAT_VERSION=6.0.45
        - APACHE_VERSION=2.2.31
    image: 89295756879.dkr.ecr.us-east-1.amazonaws.com/aurea/lyris-hq:lhq-web_v1.1
    command: /usr/local/startup.sh
    container_name: lyrishq_web
    networks:
      internal:
        aliases: ['lhq.ec2.internal']
    volumes:
    - lhq_conf:/usr/local/conf
    - lhq_webapp:/usr/local/tomcat/webapps
    - lhq_tomcat_log:/usr/local/tomcat/logs
    - lhq_apache_log:/usr/local/apache/logs
    depends_on:
    - database
    - lhq-queue
```
1. So during workspace creation Codenvy will create this folders:

/codenvy_volumes/workspace_1/lhq_conf bound to container 'lhq_web' /usr/local/conf
/codenvy_volumes/workspace_1/lhq_webapp bound to container 'lhq_web' /usr/local/tomcat/webapps
/codenvy_volumes/workspace_1/lhq_tomcat_log bound to container 'lhq_web' /usr/local/tomcat/logs
/codenvy_volumes/workspace_1/lhq_apache_log bound to container 'lhq_web' /usr/local/apache/logs

Or may be even better to create inside one more folder named under container's name like this:

/codenvy_volumes/workspace_1/lhq_web/lhq_conf bound to container 'lhq_web' /usr/local/conf
/codenvy_volumes/workspace_1/lhq_web/lhq_webapp bound to container 'lhq_web' /usr/local/tomcat/webapps
/codenvy_volumes/workspace_1/lhq_web/lhq_tomcat_log bound to container 'lhq_web' /usr/local/tomcat/logs
/codenvy_volumes/workspace_1/lhq_web/lhq_apache_log bound to container 'lhq_web' /usr/local/apache/logs
1.  If it's possible also implement read-write permissions (for example, :ro)
2. After workspace got deleted - all folders tree also got deleted.

Thank you.
